# FILE: manifests/test-pod.yaml

apiVersion: v1
kind: Pod

metadata:
  name: nginx-test-pod
  namespace: webapp

  labels:
    app: nginx-test

spec:
  containers:
  - name: nginx
    image: nginx:latest

    ports:
    - containerPort: 80